name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh 
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
                    cd Cloudin-teste
                    git pull
                    docker build --tag cloudin-teste .
                    docker run -d -p 5000:5000 cloudin-backend
